name: PR / Push Workflow

on:
  push:
    branches:
      - v0.1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install joblib scikit-learn pandas fastapi pydantic uvicorn numpy

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Train baseline model
        run: |
          python baseline.py

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: |
            model/baseline_model.joblib
            model/scaler.joblib
            model/metrics.json
