name: Release Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - "v0.2.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy joblib fastapi uvicorn

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME} .

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME}
